controller_manager:
  ros__parameters:
    update_rate: 400  # Hz

    rm_gimbal_controller:
      type: rm_gimbal_controller/RMGimbalController

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

rm_gimbal_controller:
  ros__parameters:
    pitch:
      p: 1.0
      i: 0.0
      d: 0.0
      i_clamp_max: 0.0
      i_clamp_min: 0.0
      antiwindup: false
    
    yaw:
      p: 1.0
      i: 0.0
      d: 0.0
      i_clamp_max: 0.0
      i_clamp_min: 0.0
      antiwindup: false

    sensor_name: board_c_imu

imu_sensor_broadcaster:
  ros__parameters:
    frame_id: imu
    sensor_name: board_c_imu