controller_manager:
  ros__parameters:
    update_rate: 600  # Hz

    rm_gimbal_controller:
      type: rm_gimbal_controller/RMGimbalController

rm_gimbal_controller:
  ros__parameters:
    pitch_joint:
      p: 5.0
      i: 5.0
      d: 0.3
      i_clamp_max: 1.0
      i_clamp_min: -1.0
      antiwindup: false
    
    yaw_joint:
      p: 5.0
      i: 0.0
      d: 0.2
      i_clamp_max: 0.0
      i_clamp_min: 0.0
      antiwindup: false

    sensor_name: board_c_imu
