controller_manager:
  ros__parameters:
    update_rate: 600  # Hz

    rm_gimbal_controller:
      type: rm_gimbal_controller/RMGimbalController

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

rm_gimbal_controller:
  ros__parameters:
    pitch_joint:
      p: -30000.0
      i: -5000.0
      d: 0.0
      i_clamp_max: 20000.0
      i_clamp_min: -20000.0
      antiwindup: true
    
    yaw_joint:
      p: -10000.0
      i: 0.0
      d: 0.0
      i_clamp_max: 0.0
      i_clamp_min: 0.0
      antiwindup: false

    sensor_name: board_c_imu

imu_sensor_broadcaster:
  ros__parameters:
    frame_id: imu
    sensor_name: board_c_imu